version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: simple-wms-nginx
    ports:
      - "8080:80" # frontend will call http://localhost:8080/api/...
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-wms-backend
    expose:
      - "80"
    volumes:
      - .:/var/www/html
    environment:
      - CI_ENVIRONMENT=development
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: wms-postgres
    restart: always
    environment:
      POSTGRES_USER: wms_user
      POSTGRES_PASSWORD: wms_password
      POSTGRES_DB: wms_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
